openapi: 3.0.0
info:
  version: 1.0.0
  title: Especificação relatório de desempenho de crescimento da criança
  description: Especificação relatório de desempenho de crescimento da criança
  contact:
    email: ca.chiarelli.97@gmail.com
security:
  - application:
    - read
    - write
paths:
  /accounts/{email}/progress:
    parameters:
      - name: email
        in: path
        required: true
        description: Email de identificação da conta do usuário
        schema:
          type: string
      - name: token
        in: header
        description: Token JWT no header
        required: true
        schema:
          type: array
          items:
            type: string
            format: string
        style: simple
        example: >-
          eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IlRoaWFnbyIsInN1YiI6IjEzIiwianRpIjoiZDBlMGFkZDItOTlkMC00NWY1LThlYztY2FiYzIwZjkxMGYyIiwiaWF0IjoxNTAwMDMzMjE0LCJd3RWYWxpZGF0aW9uIjoiVXN1YXJpbyIsIm5iZiI6MTUwMDAzMzIxMywiZXhwIjoxNTAwMDMzMjczLCJpc3MiOiJJc3N1ZXIiLCJhdWQiOiJBdWRpZW5jZSJ9.SmjuyXgloA2RUhIlAEetrQwfC0EhBmhu-xOMzyY3Y_Q
    get:
      summary: Recuperar progresso de crescimento das crianças pelo email da conta de usuário
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/body_response'
        400:
          description: Dados request enviados incorretos
        401:
          description: Token inválido, inexistente ou expirado
        404:
          description: Recurso {email} não encontrado
        500:
          description: Erro no servidor
components:
  schemas:
    body_response:
      type: object
      required:
        - height
        - weight
        - headCircumference
        - dateProgress
      properties:
        height:
          type: number
          example: 1,02
        weight:
          type: number
          example: 45
        headCircumference:
          type: number
          example: 0,48
        dateProgress:
          type: string
          format: date
          example: 12/12/2000
